# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c19c55f5e9471a23b9478ef9bd62665f8ac13e98e78fdeeb4438bc885afa411b8c7cab12a0cfc38520991581461de8e991766858d508de91a140fbe58414afb

test:
  secret_key_base: 98fe4a4d3d07839a1d69f1fb469e4641ec160ca254f98387a60751071020850cc16ebd5fc9ec31ecde680a4e7ee8f5f345f11e265450bc65d6233ef828af37ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
